// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cordage/v1/common.proto

package distproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnType mirrors ingest.ColumnType. Zero is reserved as an explicit
// "unspecified" sentinel (proto style), so it is intentionally NOT
// numerically aligned with ingest.ColumnType's TypeString == 0 —
// internal/distribute's conversion helpers translate between the two by
// an explicit switch, never a numeric cast, precisely so a future
// reordering of either enum can't silently corrupt the other.
type ColumnType int32

const (
	ColumnType_COLUMN_TYPE_UNSPECIFIED ColumnType = 0
	ColumnType_COLUMN_TYPE_STRING      ColumnType = 1
	ColumnType_COLUMN_TYPE_INT64       ColumnType = 2
	ColumnType_COLUMN_TYPE_FLOAT64     ColumnType = 3
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_UNSPECIFIED",
		1: "COLUMN_TYPE_STRING",
		2: "COLUMN_TYPE_INT64",
		3: "COLUMN_TYPE_FLOAT64",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_UNSPECIFIED": 0,
		"COLUMN_TYPE_STRING":      1,
		"COLUMN_TYPE_INT64":       2,
		"COLUMN_TYPE_FLOAT64":     3,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_cordage_v1_common_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_cordage_v1_common_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_cordage_v1_common_proto_rawDescGZIP(), []int{0}
}

type ColumnKind int32

const (
	ColumnKind_COLUMN_KIND_UNSPECIFIED ColumnKind = 0
	ColumnKind_COLUMN_KIND_DIMENSION   ColumnKind = 1
	ColumnKind_COLUMN_KIND_MEASURE     ColumnKind = 2
	ColumnKind_COLUMN_KIND_IGNORE      ColumnKind = 3
)

// Enum value maps for ColumnKind.
var (
	ColumnKind_name = map[int32]string{
		0: "COLUMN_KIND_UNSPECIFIED",
		1: "COLUMN_KIND_DIMENSION",
		2: "COLUMN_KIND_MEASURE",
		3: "COLUMN_KIND_IGNORE",
	}
	ColumnKind_value = map[string]int32{
		"COLUMN_KIND_UNSPECIFIED": 0,
		"COLUMN_KIND_DIMENSION":   1,
		"COLUMN_KIND_MEASURE":     2,
		"COLUMN_KIND_IGNORE":      3,
	}
)

func (x ColumnKind) Enum() *ColumnKind {
	p := new(ColumnKind)
	*p = x
	return p
}

func (x ColumnKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cordage_v1_common_proto_enumTypes[1].Descriptor()
}

func (ColumnKind) Type() protoreflect.EnumType {
	return &file_cordage_v1_common_proto_enumTypes[1]
}

func (x ColumnKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnKind.Descriptor instead.
func (ColumnKind) EnumDescriptor() ([]byte, []int) {
	return file_cordage_v1_common_proto_rawDescGZIP(), []int{1}
}

type ColumnSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ColumnType             `protobuf:"varint,2,opt,name=type,proto3,enum=cordage.v1.ColumnType" json:"type,omitempty"`
	Kind          ColumnKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=cordage.v1.ColumnKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnSchema) Reset() {
	*x = ColumnSchema{}
	mi := &file_cordage_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnSchema) ProtoMessage() {}

func (x *ColumnSchema) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnSchema.ProtoReflect.Descriptor instead.
func (*ColumnSchema) Descriptor() ([]byte, []int) {
	return file_cordage_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnSchema) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

func (x *ColumnSchema) GetKind() ColumnKind {
	if x != nil {
		return x.Kind
	}
	return ColumnKind_COLUMN_KIND_UNSPECIFIED
}

// Schema mirrors ingest.Schema. Columns is always fully populated on the
// wire: the coordinator only ever ships a schema already resolved via
// ingest.LoadSchemaFile, so there is no header-inference path over gRPC.
// has_header is set per-shard by the coordinator (true only for the
// shard covering byte offset 0, and only if the original schema declares
// a header) -- see internal/distribute.PlanShards.
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delimiter     uint32                 `protobuf:"varint,1,opt,name=delimiter,proto3" json:"delimiter,omitempty"` // a single byte value (0-255); 0 = ingest's default ','
	HasHeader     bool                   `protobuf:"varint,2,opt,name=has_header,json=hasHeader,proto3" json:"has_header,omitempty"`
	QuoteAware    bool                   `protobuf:"varint,3,opt,name=quote_aware,json=quoteAware,proto3" json:"quote_aware,omitempty"`
	Columns       []*ColumnSchema        `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_cordage_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_cordage_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetDelimiter() uint32 {
	if x != nil {
		return x.Delimiter
	}
	return 0
}

func (x *Schema) GetHasHeader() bool {
	if x != nil {
		return x.HasHeader
	}
	return false
}

func (x *Schema) GetQuoteAware() bool {
	if x != nil {
		return x.QuoteAware
	}
	return false
}

func (x *Schema) GetColumns() []*ColumnSchema {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Value mirrors ingest.Value. Exactly one oneof case is set, and *which*
// one is set is itself the type tag -- a oneof's wire encoding always
// preserves which field was written, even the zero value ("" or 0), so
// no separate ColumnType field is needed here (unlike ColumnSchema).
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_Str
	//	*Value_I64
	//	*Value_F64
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_cordage_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_cordage_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStr() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Value) GetI64() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_I64); ok {
			return x.I64
		}
	}
	return 0
}

func (x *Value) GetF64() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_F64); ok {
			return x.F64
		}
	}
	return 0
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Value_I64 struct {
	I64 int64 `protobuf:"varint,2,opt,name=i64,proto3,oneof"`
}

type Value_F64 struct {
	F64 float64 `protobuf:"fixed64,3,opt,name=f64,proto3,oneof"`
}

func (*Value_Str) isValue_Kind() {}

func (*Value_I64) isValue_Kind() {}

func (*Value_F64) isValue_Kind() {}

var File_cordage_v1_common_proto protoreflect.FileDescriptor

const file_cordage_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17cordage/v1/common.proto\x12\n" +
	"cordage.v1\"z\n" +
	"\fColumnSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.cordage.v1.ColumnTypeR\x04type\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.cordage.v1.ColumnKindR\x04kind\"\x9a\x01\n" +
	"\x06Schema\x12\x1c\n" +
	"\tdelimiter\x18\x01 \x01(\rR\tdelimiter\x12\x1d\n" +
	"\n" +
	"has_header\x18\x02 \x01(\bR\thasHeader\x12\x1f\n" +
	"\vquote_aware\x18\x03 \x01(\bR\n" +
	"quoteAware\x122\n" +
	"\acolumns\x18\x04 \x03(\v2\x18.cordage.v1.ColumnSchemaR\acolumns\"K\n" +
	"\x05Value\x12\x12\n" +
	"\x03str\x18\x01 \x01(\tH\x00R\x03str\x12\x12\n" +
	"\x03i64\x18\x02 \x01(\x03H\x00R\x03i64\x12\x12\n" +
	"\x03f64\x18\x03 \x01(\x01H\x00R\x03f64B\x06\n" +
	"\x04kind*q\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COLUMN_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11COLUMN_TYPE_INT64\x10\x02\x12\x17\n" +
	"\x13COLUMN_TYPE_FLOAT64\x10\x03*u\n" +
	"\n" +
	"ColumnKind\x12\x1b\n" +
	"\x17COLUMN_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COLUMN_KIND_DIMENSION\x10\x01\x12\x17\n" +
	"\x13COLUMN_KIND_MEASURE\x10\x02\x12\x16\n" +
	"\x12COLUMN_KIND_IGNORE\x10\x03B/Z-github.com/ysanson/cordage/internal/distprotob\x06proto3"

var (
	file_cordage_v1_common_proto_rawDescOnce sync.Once
	file_cordage_v1_common_proto_rawDescData []byte
)

func file_cordage_v1_common_proto_rawDescGZIP() []byte {
	file_cordage_v1_common_proto_rawDescOnce.Do(func() {
		file_cordage_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordage_v1_common_proto_rawDesc), len(file_cordage_v1_common_proto_rawDesc)))
	})
	return file_cordage_v1_common_proto_rawDescData
}

var file_cordage_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cordage_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cordage_v1_common_proto_goTypes = []any{
	(ColumnType)(0),      // 0: cordage.v1.ColumnType
	(ColumnKind)(0),      // 1: cordage.v1.ColumnKind
	(*ColumnSchema)(nil), // 2: cordage.v1.ColumnSchema
	(*Schema)(nil),       // 3: cordage.v1.Schema
	(*Value)(nil),        // 4: cordage.v1.Value
}
var file_cordage_v1_common_proto_depIdxs = []int32{
	0, // 0: cordage.v1.ColumnSchema.type:type_name -> cordage.v1.ColumnType
	1, // 1: cordage.v1.ColumnSchema.kind:type_name -> cordage.v1.ColumnKind
	2, // 2: cordage.v1.Schema.columns:type_name -> cordage.v1.ColumnSchema
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cordage_v1_common_proto_init() }
func file_cordage_v1_common_proto_init() {
	if File_cordage_v1_common_proto != nil {
		return
	}
	file_cordage_v1_common_proto_msgTypes[2].OneofWrappers = []any{
		(*Value_Str)(nil),
		(*Value_I64)(nil),
		(*Value_F64)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordage_v1_common_proto_rawDesc), len(file_cordage_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordage_v1_common_proto_goTypes,
		DependencyIndexes: file_cordage_v1_common_proto_depIdxs,
		EnumInfos:         file_cordage_v1_common_proto_enumTypes,
		MessageInfos:      file_cordage_v1_common_proto_msgTypes,
	}.Build()
	File_cordage_v1_common_proto = out.File
	file_cordage_v1_common_proto_goTypes = nil
	file_cordage_v1_common_proto_depIdxs = nil
}
