// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cordage/v1/coordinator.proto

package distproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryRequest carries only the AggSpec parsed from the query string.
// Everything else (schema, file path, worker addresses, on-error policy,
// batch/buffer size) is the Coordinator's own static, load-once-at-startup
// config -- M4 queries one already-configured dataset, not a per-query
// choice of file/workers.
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *AggSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_cordage_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_cordage_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetSpec() *AggSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_cordage_v1_coordinator_proto protoreflect.FileDescriptor

const file_cordage_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1ccordage/v1/coordinator.proto\x12\n" +
	"cordage.v1\x1a\x15cordage/v1/spec.proto\x1a\x17cordage/v1/result.proto\"7\n" +
	"\fQueryRequest\x12'\n" +
	"\x04spec\x18\x01 \x01(\v2\x13.cordage.v1.AggSpecR\x04spec2D\n" +
	"\vCoordinator\x125\n" +
	"\x05Query\x12\x18.cordage.v1.QueryRequest\x1a\x12.cordage.v1.ResultB/Z-github.com/ysanson/cordage/internal/distprotob\x06proto3"

var (
	file_cordage_v1_coordinator_proto_rawDescOnce sync.Once
	file_cordage_v1_coordinator_proto_rawDescData []byte
)

func file_cordage_v1_coordinator_proto_rawDescGZIP() []byte {
	file_cordage_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_cordage_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordage_v1_coordinator_proto_rawDesc), len(file_cordage_v1_coordinator_proto_rawDesc)))
	})
	return file_cordage_v1_coordinator_proto_rawDescData
}

var file_cordage_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cordage_v1_coordinator_proto_goTypes = []any{
	(*QueryRequest)(nil), // 0: cordage.v1.QueryRequest
	(*AggSpec)(nil),      // 1: cordage.v1.AggSpec
	(*Result)(nil),       // 2: cordage.v1.Result
}
var file_cordage_v1_coordinator_proto_depIdxs = []int32{
	1, // 0: cordage.v1.QueryRequest.spec:type_name -> cordage.v1.AggSpec
	0, // 1: cordage.v1.Coordinator.Query:input_type -> cordage.v1.QueryRequest
	2, // 2: cordage.v1.Coordinator.Query:output_type -> cordage.v1.Result
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cordage_v1_coordinator_proto_init() }
func file_cordage_v1_coordinator_proto_init() {
	if File_cordage_v1_coordinator_proto != nil {
		return
	}
	file_cordage_v1_spec_proto_init()
	file_cordage_v1_result_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordage_v1_coordinator_proto_rawDesc), len(file_cordage_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cordage_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_cordage_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_cordage_v1_coordinator_proto_msgTypes,
	}.Build()
	File_cordage_v1_coordinator_proto = out.File
	file_cordage_v1_coordinator_proto_goTypes = nil
	file_cordage_v1_coordinator_proto_depIdxs = nil
}
