// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cordage/v1/spec.proto

package distproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FuncKind mirrors aggregate.AggFuncKind. FUNC_KIND_PERCENTILE is
// included, deliberately, for forward/wire compatibility -- a future
// milestone that adds distributed percentile merging doesn't need a
// breaking field renumber. But M3 rejects it outright: both the
// coordinator and WorkerServer call aggregate.ValidateDistributable
// before doing any work, so a Percentile measure fails fast with a clear
// error instead of silently under-aggregating (t-digest/centroid state
// has no wire representation in M3 -- see MeasureState in state.proto).
type FuncKind int32

const (
	FuncKind_FUNC_KIND_UNSPECIFIED FuncKind = 0
	FuncKind_FUNC_KIND_SUM         FuncKind = 1
	FuncKind_FUNC_KIND_MIN         FuncKind = 2
	FuncKind_FUNC_KIND_MAX         FuncKind = 3
	FuncKind_FUNC_KIND_AVG         FuncKind = 4
	FuncKind_FUNC_KIND_DISTINCT    FuncKind = 5
	FuncKind_FUNC_KIND_PERCENTILE  FuncKind = 6 // present for schema evolution; always rejected in M3
)

// Enum value maps for FuncKind.
var (
	FuncKind_name = map[int32]string{
		0: "FUNC_KIND_UNSPECIFIED",
		1: "FUNC_KIND_SUM",
		2: "FUNC_KIND_MIN",
		3: "FUNC_KIND_MAX",
		4: "FUNC_KIND_AVG",
		5: "FUNC_KIND_DISTINCT",
		6: "FUNC_KIND_PERCENTILE",
	}
	FuncKind_value = map[string]int32{
		"FUNC_KIND_UNSPECIFIED": 0,
		"FUNC_KIND_SUM":         1,
		"FUNC_KIND_MIN":         2,
		"FUNC_KIND_MAX":         3,
		"FUNC_KIND_AVG":         4,
		"FUNC_KIND_DISTINCT":    5,
		"FUNC_KIND_PERCENTILE":  6,
	}
)

func (x FuncKind) Enum() *FuncKind {
	p := new(FuncKind)
	*p = x
	return p
}

func (x FuncKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FuncKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cordage_v1_spec_proto_enumTypes[0].Descriptor()
}

func (FuncKind) Type() protoreflect.EnumType {
	return &file_cordage_v1_spec_proto_enumTypes[0]
}

func (x FuncKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FuncKind.Descriptor instead.
func (FuncKind) EnumDescriptor() ([]byte, []int) {
	return file_cordage_v1_spec_proto_rawDescGZIP(), []int{0}
}

type AggFunc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          FuncKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=cordage.v1.FuncKind" json:"kind,omitempty"`
	Quantile      float64                `protobuf:"fixed64,2,opt,name=quantile,proto3" json:"quantile,omitempty"` // meaningful only when kind == FUNC_KIND_PERCENTILE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggFunc) Reset() {
	*x = AggFunc{}
	mi := &file_cordage_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggFunc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggFunc) ProtoMessage() {}

func (x *AggFunc) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggFunc.ProtoReflect.Descriptor instead.
func (*AggFunc) Descriptor() ([]byte, []int) {
	return file_cordage_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AggFunc) GetKind() FuncKind {
	if x != nil {
		return x.Kind
	}
	return FuncKind_FUNC_KIND_UNSPECIFIED
}

func (x *AggFunc) GetQuantile() float64 {
	if x != nil {
		return x.Quantile
	}
	return 0
}

type MeasureSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Funcs         []*AggFunc             `protobuf:"bytes,2,rep,name=funcs,proto3" json:"funcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureSpec) Reset() {
	*x = MeasureSpec{}
	mi := &file_cordage_v1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureSpec) ProtoMessage() {}

func (x *MeasureSpec) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureSpec.ProtoReflect.Descriptor instead.
func (*MeasureSpec) Descriptor() ([]byte, []int) {
	return file_cordage_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *MeasureSpec) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *MeasureSpec) GetFuncs() []*AggFunc {
	if x != nil {
		return x.Funcs
	}
	return nil
}

type AggSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupBy       []string               `protobuf:"bytes,1,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Measures      []*MeasureSpec         `protobuf:"bytes,2,rep,name=measures,proto3" json:"measures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggSpec) Reset() {
	*x = AggSpec{}
	mi := &file_cordage_v1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggSpec) ProtoMessage() {}

func (x *AggSpec) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggSpec.ProtoReflect.Descriptor instead.
func (*AggSpec) Descriptor() ([]byte, []int) {
	return file_cordage_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *AggSpec) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *AggSpec) GetMeasures() []*MeasureSpec {
	if x != nil {
		return x.Measures
	}
	return nil
}

var File_cordage_v1_spec_proto protoreflect.FileDescriptor

const file_cordage_v1_spec_proto_rawDesc = "" +
	"\n" +
	"\x15cordage/v1/spec.proto\x12\n" +
	"cordage.v1\"O\n" +
	"\aAggFunc\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.cordage.v1.FuncKindR\x04kind\x12\x1a\n" +
	"\bquantile\x18\x02 \x01(\x01R\bquantile\"P\n" +
	"\vMeasureSpec\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12)\n" +
	"\x05funcs\x18\x02 \x03(\v2\x13.cordage.v1.AggFuncR\x05funcs\"Y\n" +
	"\aAggSpec\x12\x19\n" +
	"\bgroup_by\x18\x01 \x03(\tR\agroupBy\x123\n" +
	"\bmeasures\x18\x02 \x03(\v2\x17.cordage.v1.MeasureSpecR\bmeasures*\xa3\x01\n" +
	"\bFuncKind\x12\x19\n" +
	"\x15FUNC_KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rFUNC_KIND_SUM\x10\x01\x12\x11\n" +
	"\rFUNC_KIND_MIN\x10\x02\x12\x11\n" +
	"\rFUNC_KIND_MAX\x10\x03\x12\x11\n" +
	"\rFUNC_KIND_AVG\x10\x04\x12\x16\n" +
	"\x12FUNC_KIND_DISTINCT\x10\x05\x12\x18\n" +
	"\x14FUNC_KIND_PERCENTILE\x10\x06B/Z-github.com/ysanson/cordage/internal/distprotob\x06proto3"

var (
	file_cordage_v1_spec_proto_rawDescOnce sync.Once
	file_cordage_v1_spec_proto_rawDescData []byte
)

func file_cordage_v1_spec_proto_rawDescGZIP() []byte {
	file_cordage_v1_spec_proto_rawDescOnce.Do(func() {
		file_cordage_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordage_v1_spec_proto_rawDesc), len(file_cordage_v1_spec_proto_rawDesc)))
	})
	return file_cordage_v1_spec_proto_rawDescData
}

var file_cordage_v1_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cordage_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cordage_v1_spec_proto_goTypes = []any{
	(FuncKind)(0),       // 0: cordage.v1.FuncKind
	(*AggFunc)(nil),     // 1: cordage.v1.AggFunc
	(*MeasureSpec)(nil), // 2: cordage.v1.MeasureSpec
	(*AggSpec)(nil),     // 3: cordage.v1.AggSpec
}
var file_cordage_v1_spec_proto_depIdxs = []int32{
	0, // 0: cordage.v1.AggFunc.kind:type_name -> cordage.v1.FuncKind
	1, // 1: cordage.v1.MeasureSpec.funcs:type_name -> cordage.v1.AggFunc
	2, // 2: cordage.v1.AggSpec.measures:type_name -> cordage.v1.MeasureSpec
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cordage_v1_spec_proto_init() }
func file_cordage_v1_spec_proto_init() {
	if File_cordage_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordage_v1_spec_proto_rawDesc), len(file_cordage_v1_spec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordage_v1_spec_proto_goTypes,
		DependencyIndexes: file_cordage_v1_spec_proto_depIdxs,
		EnumInfos:         file_cordage_v1_spec_proto_enumTypes,
		MessageInfos:      file_cordage_v1_spec_proto_msgTypes,
	}.Build()
	File_cordage_v1_spec_proto = out.File
	file_cordage_v1_spec_proto_goTypes = nil
	file_cordage_v1_spec_proto_depIdxs = nil
}
