// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cordage/v1/state.proto

package distproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeasureState is one measure column's raw, mergeable accumulator
// state -- the wire form of aggregate.MeasureState. There is
// deliberately no field for t-digest/percentile state: distributed
// percentile merging is out of scope for M3 (see FuncKind in
// spec.proto), so no AggSpec that reaches this message may contain a
// Percentile measure -- aggregate.ValidateDistributable rejects it
// before a ShardRequest is ever built or a ShardResult ever produced.
type MeasureState struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ColType    ColumnType             `protobuf:"varint,1,opt,name=col_type,json=colType,proto3,enum=cordage.v1.ColumnType" json:"col_type,omitempty"`
	SumI64     int64                  `protobuf:"varint,2,opt,name=sum_i64,json=sumI64,proto3" json:"sum_i64,omitempty"`
	MinI64     int64                  `protobuf:"varint,3,opt,name=min_i64,json=minI64,proto3" json:"min_i64,omitempty"`
	MaxI64     int64                  `protobuf:"varint,4,opt,name=max_i64,json=maxI64,proto3" json:"max_i64,omitempty"`
	SumF64     float64                `protobuf:"fixed64,5,opt,name=sum_f64,json=sumF64,proto3" json:"sum_f64,omitempty"`
	MinF64     float64                `protobuf:"fixed64,6,opt,name=min_f64,json=minF64,proto3" json:"min_f64,omitempty"`
	MaxF64     float64                `protobuf:"fixed64,7,opt,name=max_f64,json=maxF64,proto3" json:"max_f64,omitempty"`
	HaveMinMax bool                   `protobuf:"varint,8,opt,name=have_min_max,json=haveMinMax,proto3" json:"have_min_max,omitempty"`
	// Empty unless this measure requested Distinct. When present, always
	// exactly 16384 bytes (1 byte per HyperLogLog register, at
	// aggregate's fixed precision=14). Register-wise max is exact and
	// order-independent, so this byte slice round-trips through gRPC
	// with zero precision loss.
	HllRegisters  []byte `protobuf:"bytes,9,opt,name=hll_registers,json=hllRegisters,proto3" json:"hll_registers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureState) Reset() {
	*x = MeasureState{}
	mi := &file_cordage_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureState) ProtoMessage() {}

func (x *MeasureState) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureState.ProtoReflect.Descriptor instead.
func (*MeasureState) Descriptor() ([]byte, []int) {
	return file_cordage_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *MeasureState) GetColType() ColumnType {
	if x != nil {
		return x.ColType
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

func (x *MeasureState) GetSumI64() int64 {
	if x != nil {
		return x.SumI64
	}
	return 0
}

func (x *MeasureState) GetMinI64() int64 {
	if x != nil {
		return x.MinI64
	}
	return 0
}

func (x *MeasureState) GetMaxI64() int64 {
	if x != nil {
		return x.MaxI64
	}
	return 0
}

func (x *MeasureState) GetSumF64() float64 {
	if x != nil {
		return x.SumF64
	}
	return 0
}

func (x *MeasureState) GetMinF64() float64 {
	if x != nil {
		return x.MinF64
	}
	return 0
}

func (x *MeasureState) GetMaxF64() float64 {
	if x != nil {
		return x.MaxF64
	}
	return 0
}

func (x *MeasureState) GetHaveMinMax() bool {
	if x != nil {
		return x.HaveMinMax
	}
	return false
}

func (x *MeasureState) GetHllRegisters() []byte {
	if x != nil {
		return x.HllRegisters
	}
	return nil
}

type GroupState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []*Value               `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Measures      []*MeasureState        `protobuf:"bytes,3,rep,name=measures,proto3" json:"measures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupState) Reset() {
	*x = GroupState{}
	mi := &file_cordage_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupState) ProtoMessage() {}

func (x *GroupState) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupState.ProtoReflect.Descriptor instead.
func (*GroupState) Descriptor() ([]byte, []int) {
	return file_cordage_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *GroupState) GetKey() []*Value {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GroupState) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GroupState) GetMeasures() []*MeasureState {
	if x != nil {
		return x.Measures
	}
	return nil
}

var File_cordage_v1_state_proto protoreflect.FileDescriptor

const file_cordage_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x16cordage/v1/state.proto\x12\n" +
	"cordage.v1\x1a\x17cordage/v1/common.proto\"\x9e\x02\n" +
	"\fMeasureState\x121\n" +
	"\bcol_type\x18\x01 \x01(\x0e2\x16.cordage.v1.ColumnTypeR\acolType\x12\x17\n" +
	"\asum_i64\x18\x02 \x01(\x03R\x06sumI64\x12\x17\n" +
	"\amin_i64\x18\x03 \x01(\x03R\x06minI64\x12\x17\n" +
	"\amax_i64\x18\x04 \x01(\x03R\x06maxI64\x12\x17\n" +
	"\asum_f64\x18\x05 \x01(\x01R\x06sumF64\x12\x17\n" +
	"\amin_f64\x18\x06 \x01(\x01R\x06minF64\x12\x17\n" +
	"\amax_f64\x18\a \x01(\x01R\x06maxF64\x12 \n" +
	"\fhave_min_max\x18\b \x01(\bR\n" +
	"haveMinMax\x12#\n" +
	"\rhll_registers\x18\t \x01(\fR\fhllRegisters\"}\n" +
	"\n" +
	"GroupState\x12#\n" +
	"\x03key\x18\x01 \x03(\v2\x11.cordage.v1.ValueR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x124\n" +
	"\bmeasures\x18\x03 \x03(\v2\x18.cordage.v1.MeasureStateR\bmeasuresB/Z-github.com/ysanson/cordage/internal/distprotob\x06proto3"

var (
	file_cordage_v1_state_proto_rawDescOnce sync.Once
	file_cordage_v1_state_proto_rawDescData []byte
)

func file_cordage_v1_state_proto_rawDescGZIP() []byte {
	file_cordage_v1_state_proto_rawDescOnce.Do(func() {
		file_cordage_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordage_v1_state_proto_rawDesc), len(file_cordage_v1_state_proto_rawDesc)))
	})
	return file_cordage_v1_state_proto_rawDescData
}

var file_cordage_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cordage_v1_state_proto_goTypes = []any{
	(*MeasureState)(nil), // 0: cordage.v1.MeasureState
	(*GroupState)(nil),   // 1: cordage.v1.GroupState
	(ColumnType)(0),      // 2: cordage.v1.ColumnType
	(*Value)(nil),        // 3: cordage.v1.Value
}
var file_cordage_v1_state_proto_depIdxs = []int32{
	2, // 0: cordage.v1.MeasureState.col_type:type_name -> cordage.v1.ColumnType
	3, // 1: cordage.v1.GroupState.key:type_name -> cordage.v1.Value
	0, // 2: cordage.v1.GroupState.measures:type_name -> cordage.v1.MeasureState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cordage_v1_state_proto_init() }
func file_cordage_v1_state_proto_init() {
	if File_cordage_v1_state_proto != nil {
		return
	}
	file_cordage_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordage_v1_state_proto_rawDesc), len(file_cordage_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordage_v1_state_proto_goTypes,
		DependencyIndexes: file_cordage_v1_state_proto_depIdxs,
		MessageInfos:      file_cordage_v1_state_proto_msgTypes,
	}.Build()
	File_cordage_v1_state_proto = out.File
	file_cordage_v1_state_proto_goTypes = nil
	file_cordage_v1_state_proto_depIdxs = nil
}
