// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cordage/v1/worker.proto

package distproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShardRequest assigns one worker a single, already newline-aligned byte
// range of a file the worker must be able to open *independently* -- a
// shared filesystem path/mount. M3 does not ship file bytes over the
// wire (that's a fast-follow, e.g. for a cross-host deployment); the
// milestone's own exit criteria (a local multi-process test on one
// machine) only require a shared local path, which this satisfies
// directly.
type ShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Spec          *AggSpec               `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	OnError       string                 `protobuf:"bytes,6,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`           // "skip" or "fail", mirrors ingest.ErrorPolicy
	BatchSize     int32                  `protobuf:"varint,7,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`    // 0 = ingest package default
	BufferSize    int32                  `protobuf:"varint,8,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"` // 0 = ingest package default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardRequest) Reset() {
	*x = ShardRequest{}
	mi := &file_cordage_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRequest) ProtoMessage() {}

func (x *ShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRequest.ProtoReflect.Descriptor instead.
func (*ShardRequest) Descriptor() ([]byte, []int) {
	return file_cordage_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ShardRequest) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ShardRequest) GetSpec() *AggSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ShardRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ShardRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ShardRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ShardRequest) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

func (x *ShardRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ShardRequest) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

// ShardResult is one shard's raw, mergeable partial result. Its size is
// O(#groups), not O(#rows) -- a shard's row count can be arbitrarily
// large without inflating the response (though a high-cardinality
// GROUP BY combined with many Distinct measures can still grow this
// message past gRPC's default max message size; not a concern at this
// milestone's benchmark dataset scale).
type ShardResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupState          `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Rows          int64                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Skipped       int64                  `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardResult) Reset() {
	*x = ShardResult{}
	mi := &file_cordage_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardResult) ProtoMessage() {}

func (x *ShardResult) ProtoReflect() protoreflect.Message {
	mi := &file_cordage_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardResult.ProtoReflect.Descriptor instead.
func (*ShardResult) Descriptor() ([]byte, []int) {
	return file_cordage_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ShardResult) GetGroups() []*GroupState {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ShardResult) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ShardResult) GetSkipped() int64 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

var File_cordage_v1_worker_proto protoreflect.FileDescriptor

const file_cordage_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x17cordage/v1/worker.proto\x12\n" +
	"cordage.v1\x1a\x17cordage/v1/common.proto\x1a\x15cordage/v1/spec.proto\x1a\x16cordage/v1/state.proto\"\x8b\x02\n" +
	"\fShardRequest\x12*\n" +
	"\x06schema\x18\x01 \x01(\v2\x12.cordage.v1.SchemaR\x06schema\x12'\n" +
	"\x04spec\x18\x02 \x01(\v2\x13.cordage.v1.AggSpecR\x04spec\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x03R\x06length\x12\x19\n" +
	"\bon_error\x18\x06 \x01(\tR\aonError\x12\x1d\n" +
	"\n" +
	"batch_size\x18\a \x01(\x05R\tbatchSize\x12\x1f\n" +
	"\vbuffer_size\x18\b \x01(\x05R\n" +
	"bufferSize\"k\n" +
	"\vShardResult\x12.\n" +
	"\x06groups\x18\x01 \x03(\v2\x16.cordage.v1.GroupStateR\x06groups\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x03R\x04rows\x12\x18\n" +
	"\askipped\x18\x03 \x01(\x03R\askipped2G\n" +
	"\x06Worker\x12=\n" +
	"\bRunShard\x12\x18.cordage.v1.ShardRequest\x1a\x17.cordage.v1.ShardResultB/Z-github.com/ysanson/cordage/internal/distprotob\x06proto3"

var (
	file_cordage_v1_worker_proto_rawDescOnce sync.Once
	file_cordage_v1_worker_proto_rawDescData []byte
)

func file_cordage_v1_worker_proto_rawDescGZIP() []byte {
	file_cordage_v1_worker_proto_rawDescOnce.Do(func() {
		file_cordage_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordage_v1_worker_proto_rawDesc), len(file_cordage_v1_worker_proto_rawDesc)))
	})
	return file_cordage_v1_worker_proto_rawDescData
}

var file_cordage_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cordage_v1_worker_proto_goTypes = []any{
	(*ShardRequest)(nil), // 0: cordage.v1.ShardRequest
	(*ShardResult)(nil),  // 1: cordage.v1.ShardResult
	(*Schema)(nil),       // 2: cordage.v1.Schema
	(*AggSpec)(nil),      // 3: cordage.v1.AggSpec
	(*GroupState)(nil),   // 4: cordage.v1.GroupState
}
var file_cordage_v1_worker_proto_depIdxs = []int32{
	2, // 0: cordage.v1.ShardRequest.schema:type_name -> cordage.v1.Schema
	3, // 1: cordage.v1.ShardRequest.spec:type_name -> cordage.v1.AggSpec
	4, // 2: cordage.v1.ShardResult.groups:type_name -> cordage.v1.GroupState
	0, // 3: cordage.v1.Worker.RunShard:input_type -> cordage.v1.ShardRequest
	1, // 4: cordage.v1.Worker.RunShard:output_type -> cordage.v1.ShardResult
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cordage_v1_worker_proto_init() }
func file_cordage_v1_worker_proto_init() {
	if File_cordage_v1_worker_proto != nil {
		return
	}
	file_cordage_v1_common_proto_init()
	file_cordage_v1_spec_proto_init()
	file_cordage_v1_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordage_v1_worker_proto_rawDesc), len(file_cordage_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cordage_v1_worker_proto_goTypes,
		DependencyIndexes: file_cordage_v1_worker_proto_depIdxs,
		MessageInfos:      file_cordage_v1_worker_proto_msgTypes,
	}.Build()
	File_cordage_v1_worker_proto = out.File
	file_cordage_v1_worker_proto_goTypes = nil
	file_cordage_v1_worker_proto_depIdxs = nil
}
